remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

title: "Rodolfo Lomanto"
description: "PortfÃ³lio de AnÃ¡lise de Dados, AutomaÃ§Ã£o e Business Intelligence"


navigation: true

# Menu padrÃ£o em portuguÃªs
nav: nav_pt

# Defaults para cada idioma
defaults:
  # PÃGINAS EM PORTUGUÃŠS
  - scope:
      path: ""
    values:
      lang: "pt-BR"
      layout: single

  # PÃGINAS EM INGLÃŠS
  - scope:
      path: "en"
    values:
      lang: "en"
      layout: single

# MENU PT-BR
nav_pt:
  - title: "InÃ­cio"
    url: /
  - title: "Sobre"
    url: /sobre/
  - title: "Projetos"
    url: /projetos/
  - title: "Contato"
    url: /contato/
  - title: "ğŸ‡ºğŸ‡¸"
    url: /en/
    class: language-switch


# MENU EN
nav_en:
  - title: "Home"
    url: /en/
  - title: "About"
    url: /en/about/
  - title: "Projects"
    url: /en/projects/
  - title: "Contact"
    url: /en/contact/
  - title: "ğŸ‡§ğŸ‡·"
    url: /
    class: language-switch

# Arquivo CSS customizado
sass:
  sass_dir: "assets/css"


