title: "Rodolfo Lomanto"
description: "Portfólio de Análise de Dados, Automação e Aplicativos"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown

locale: "pt-BR"

include:
  - _pages

