remote_theme: "mmistakes/minimal-mistakes@4.27.3"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
- jekyll-include-cache
- jekyll-remote-theme

title: [The title of your site]
description: [A short description of your site's purpose]