# Usar navegaÃ§Ã£o customizada
header_pages:


remote_theme: "mmistakes/minimal-mistakes@4.27.3"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
- jekyll-include-cache
- jekyll-remote-theme

title: "Rodolfo Lomanto"
description: "PortfÃ³lio de AnÃ¡lise de Dados, AutomaÃ§Ã£o, BI e CriaÃ§Ã£o de Aplicativos"

# IDIOMA PADRÃƒO
locale: "pt-BR"

# MENU PT
nav_pt:
  - title: "InÃ­cio"
    url: /
  - title: "Sobre"
    url: /sobre/
  - title: "Projetos"
    url: /projetos/
  - title: "Contato"
    url: /contato/
  - title: "EN ğŸ‡ºğŸ‡¸"
    url: /en/

# MENU EN
nav_en:
  - title: "Home"
    url: /en/
  - title: "About"
    url: /en/about/
  - title: "Projects"
    url: /en/projects/
  - title: "Contact"
    url: /en/contact/
  - title: "PT ğŸ‡§ğŸ‡·"
    url: /

# NavegaÃ§Ã£o
nav:
  - title: "InÃ­cio"
    url: /
  - title: "Sobre"
    url: /sobre/
  - title: "Projetos"
    url: /projetos/
  - title: "Contato"
    url: /contato/
