title: "Rodolfo Lomanto"
description: "Portfólio de Análise de Dados, Automação e Aplicativos"

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

# Aparência
minimal_mistakes_skin: "default"

# Linguagem
locale: "pt-BR"

markdown: kramdown

# Páginas
include:
  - _pages





